In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
data = np.array([[3, -1.5, 2, -5.4], [0, 4, -0.3, 2.1], [1, 3.3, -1.9, -4.3]])

In [3]:
data_standardized = preprocessing.scale(data)
print("Mean = ", data_standardized.mean(axis=0))
print("Std Deviation = ", data_standardized.std(axis=0))

Mean =  [  5.55111512e-17  -1.11022302e-16  -7.40148683e-17  -7.40148683e-17]
Std Deviation =  [ 1.  1.  1.  1.]


In [6]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print("Min max scaled data = ", data_scaled)

Min max scaled data =  [[ 1.          0.          1.          0.        ]
 [ 0.          1.          0.41025641  1.        ]
 [ 0.33333333  0.87272727  0.          0.14666667]]


In [8]:
data_normalised = preprocessing.normalize(data, norm='l1')
print("L1 normalized data = ", data_normalised)

L1 normalized data =  [[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


In [9]:
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print("Binarized data = ", data_binarized)

Binarized data =  [[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  1.  0.  0.]]


In [15]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0,2,1,12],[1,3,5,3],[2,3,2,12],[1,2,4,3]])
encoded_vector = encoder.transform([[2,3,5,3]]).toarray()
print("Encoded Vector = ", encoded_vector)

Encoded Vector =  [[ 0.  0.  1.  0.  1.  0.  0.  0.  1.  1.  0.]]
